[package]
name = "sui-indexer-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
description = "Storage layer for Sui Indexer"
rust-version.workspace = true
keywords = ["sui", "postgres", "indexer", "sqlx"]
categories = ["database", "cryptography::blockchain"]
readme = "../../README.md"

[dependencies]
# Workspace dependencies
sqlx = { workspace = true, features = ["bigdecimal"] }
sui-indexer-config = { path = "../sui-indexer-config" }
sui-indexer-events = { path = "../sui-indexer-events" }

# Serialization
serde.workspace = true
serde_json.workspace = true

# Error handling
eyre.workspace = true

# Traits
async-trait.workspace = true

# Data structures
chrono.workspace = true
uuid.workspace = true

# Tracing
tracing.workspace = true

# Hex encoding for BYTEA gateway output
chain-core = { version = "0.1.0", path = "../chain-core" }
hex.workspace = true

[dev-dependencies]
sui-json-rpc-types.workspace = true
sui-types.workspace = true
tokio.workspace = true

[lints]
workspace = true
