[package]
name = "sui-indexer-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "CLI interface for the Sui Indexer Framework"

[[bin]]
name = "sui-indexer"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
sui-indexer-config = { path = "../../crates/sui-indexer-config" }
sui-indexer-core = { path = "../../crates/sui-indexer-core" }

# CLI dependencies
clap.workspace = true
eyre.workspace = true

# Async runtime
tokio.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true
